### ISSUE TITLE
raise Exception("Failed to get observation after 100 tries, environment is down.")

### ISSUE THREAD

**Issue by zhengluohu** [FredericoMetelo/TaskOffloadingAgentLibrary#7] opened 2024-06-12 11:47 UTC
When running the DebugEnv.py file, I encountered an issue during the environment reset. The error message "self.__get_obs() raises the Exception: 'Failed to get observation after 100 tries, environment is down.'" appears. What could be causing this issue, and how should I troubleshoot and resolve it? I appreciate any response. Thank you very much.
![image](https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/ad59b79b-3b39-4c83-91ca-7ba6df0fc2ee)

**Comment by zhengluohu** [comment] 2024-06-13 02:41
<img width="954" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/96e39b25-229a-40c0-b347-86613fa54e70">
I have already installed the environment according to the instructions on https://github.com/FredericoMetelo/peersim-environment/tree/master.

**Comment by FredericoMetelo** [comment] 2024-06-14 13:25
Sorry for the delay. Does that happen on the first time you call reset (On environment creation) or one full simulation cycle/episode into the training?

**Comment by FredericoMetelo** [comment] 2024-06-14 13:27
For now could you also share what version of the java you are running?

**Comment by zhengluohu** [comment] 2024-06-16 10:58
Thank you for your response. This issue occurs during the first call to reset (on environment creation). The version of java is 17.0.5. To identify the issue, I have repeated the steps of setting up my environment and documented them as follows. If there are any problems with any of the steps, please point them out. Thank you very much.

1.	Install Java (version 17.0.5)
1.1: mkdir java and cd java
1.2: wget https://download.oracle.com/java/17/archive/jdk-17.0.5_linux-x64_bin.tar.gz
1.3: tar -zxvf jdk-17.0.5_linux-x64_bin.tar.gz
1.4: vim /etc/profile
1.5  
export JAVA_HOME=/root/java/jdk-17.0.5
export PATH=$PATH:$JAVA_HOME/bin;
export CLASSPATH=:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar;
1..6: source /etc/profile
1.7 java -version
 
<img width="292" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/ee784f2b-2651-408e-bdb7-58d87e2c525e">

2.	install Maven (version 3.8.6)
2.1 mkdir Maven 
2.2 cd Maven
2.3 wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
2.4 tar -zxvf apache-maven-3.8.6-bin.tar.gz
2.5 
export MAVEN_HOME=/root/Maven/apache-maven-3.8.6
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
2.6	source /etc/profile
2.7	mvn -version
 
<img width="297" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/6bdf9578-4790-4f00-85d7-3d0c5dd29bfe">

2.8	echo $PATH
 
<img width="416" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/29f25f8c-3a30-43f1-8cb6-729eee112db3">

3.	Setup the anaconda environment
3.1 git clone https://github.com/FredericoMetelo/peersim-environment.git
  3.2 conda env create -f /root/peersim-environment/Setup/environment.yml
  3.2 conda activate PeersimGym
  3.4 cd /root/peersim-environment/src/peersim-gym
  3.5 pip install --no-build-isolation --no-deps -e .
 
<img width="416" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/e0fa967c-371a-4c6a-abba-fc8092a38c97">

4.	Use the environment
4.1 git clone https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary.git
4.2 run src/Debug.py
4.3 FileNotFoundError: [Errno 2] No such file or directory: 'logs/log_run_1.txt'
4.4 log_dir=’logs/’ was changed to log_dir=None
4.5  
<img width="416" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/8185a214-8ea7-4426-95b4-0655b4220b8e">

**Comment by FredericoMetelo** [comment] 2024-06-17 09:17
Alright, are you using WSL? If so, it will be hard to help you, I would recommend using the windows version directly.
If you are on Linux I don't think the problem is with your setup. Lets try this steps to, hopefully, fix the problem:
1. There are some  other paths you may need to change, namely if you are using the AWS cluster based workload (in DebugEnv.py see if ```simtype = "basic-workload"```) then you will need to change the path of the workload file in your config_dict. Look for ```workloadPath="/home/fm/IdeaProjects/peersim-environment/Datasets/alibaba_trace_cleaned.json",``` and change the ```/home/fm/IdeaProjects/peersim-environment/``` to where you pulled the environment repo. Confirm it, but from the steps for setting env I think you need ```/root/peersim-environment/Datasets```.
2. Compile the environment yourself. Please follow the `Developing the simulation` instructions on the peersim-environment repository.
3. Create a log dir and set 'log_dir='<TheNameOfTheDirYouCreated>". Then please share the contents of the log file.

**Comment by zhengluohu** [comment] 2024-06-19 11:26
Yes, you are right. I am running the environment on a Linux system under Cluster. After changing the workloadPath, it worked successfully. Thank you for your help. Much appreciated.
![image](https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/66994045/6509042c-8a99-4afd-952d-1310837ef25b)

**Comment by FredericoMetelo** [comment] 2024-06-20 08:55
Nice! I'll close the issue now.

**Closed as completed by FredericoMetelo** 2024-06-20 08:55 UTC
